from django.conf.urls import url
from django.contrib import admin 
from . import views

app = 'web1'

urlpatterns = [
    url(r'^register/', views.user_register, name='user_register'),
    url(r'^logout/', views.user_logout, name='user_logout'),
    url(r'^special/', views.special, name='special'),
    url(r'^index/', views.index, name='index'),
    url(r'^login/', views.user_login,  name='user_login'),
	url(r'^index1/', views.index1, name='index1'),
    url(r'^finance/', views.finance, name='finance'),
    url(r'^finance1/', views.fin_asst, name='fin_asst'),
    url(r'^finance2/', views.fin_asst2, name='fin_asst2'),
    url(r'^finance3/', views.fin_asst3, name='fin_asst3'),
    url(r'^finance4/', views.fin_asst4, name='fin_asst4'),
    url(r'^travel/', views.travel, name='travel'),
    url(r'^travel1/', views.travel_grant, name='travel_grant'),
    url(r'^travel2/', views.travel_grant2, name='travel_grant2'),
    url(r'^travel3/', views.travel_grant3, name='travel_grant3'),
    url(r'^travel4/', views.travel_grant4, name='travel_grant4'),
    url(r'^symposium/', views.symposium, name='symposium'),
	url(r'^symposium1/', views.symposium1, name='symposium1'),
    url(r'^symposium2/', views.symposium2, name='symposium2'),
    url(r'^symposium3/', views.symposium3, name='symposium3'),
    url(r'^symposium4/', views.symposium4, name='symposium4'),
    url(r'^viewf1', views.showf, name='viewf'),
    url(r'^(?P<id>\d+)/editf1/$', views.editf, name='editf'), 
    url(r'^deletef1/(?P<id>\d+)/$', views.deletef, name='deletef'),
    url(r'^updatef1/(?P<id>\d+)/$',  views.updatef, name='updatef'),
    url(r'^viewf2', views.showf2, name='viewf2'),
    url(r'^(?P<id>\d+)/editf2/$', views.editf2, name='editf2'), 
    url(r'^deletef2/(?P<id>\d+)/$', views.deletef2, name='deletef2'),
    url(r'^updatef2/(?P<id>\d+)/$',  views.updatef2, name='updatef2'),
    url(r'^viewf3', views.showf3, name='viewf3'),
    url(r'^(?P<id>\d+)/editf3/$', views.editf3, name='editf3'), 
    url(r'^deletef3/(?P<id>\d+)/$', views.deletef3, name='deletef3'),
    url(r'^updatef3/(?P<id>\d+)/$',  views.updatef3, name='updatef3'),
    url(r'^viewf4', views.showf4, name='viewf4'),
    url(r'^(?P<id>\d+)/editf4/$', views.editf4, name='editf4'), 
    url(r'^deletef4/(?P<id>\d+)/$', views.deletef4, name='deletef4'),
    url(r'^updatef4/(?P<id>\d+)/$',  views.updatef4, name='updatef4'),
    url(r'^viewt1', views.showt1, name='viewt1'),
    url(r'^(?P<id>\d+)/editt1/$', views.editt1, name='editt1'), 
    url(r'^deletet1/(?P<id>\d+)/$', views.deletet1, name='deletet1'),
    url(r'^updatet1/(?P<id>\d+)/$',  views.updatet1, name='updatet1'),
    url(r'^viewt2', views.showt2, name='viewt2'),
    url(r'^(?P<id>\d+)/editt2/$', views.editt2, name='editt2'), 
    url(r'^deletet2/(?P<id>\d+)/$', views.deletet2, name='deletet2'),
    url(r'^updatet2/(?P<id>\d+)/$',  views.updatet2, name='updatet2'),
    url(r'^viewt3', views.showt3, name='viewt3'),
    url(r'^(?P<id>\d+)/editt3/$', views.editt3, name='editt3'), 
    url(r'^deletet3/(?P<id>\d+)/$', views.deletet3, name='deletet3'),
    url(r'^updatet3/(?P<id>\d+)/$',  views.updatet3, name='updatet3'),
    url(r'^viewt4', views.showt4, name='viewt4'),
    url(r'^(?P<id>\d+)/editt4/$', views.editt4, name='editt4'), 
    url(r'^deletet4/(?P<id>\d+)/$', views.deletet4, name='deletet4'),
    url(r'^updatet4/(?P<id>\d+)/$',  views.updatet4, name='updatet4'),
    url(r'^views1', views.shows1, name='views1'),
    url(r'^(?P<id>\d+)/edits1/$', views.edits1, name='edits1'), 
    url(r'^deletes1/(?P<id>\d+)/$', views.deletes1, name='deletes1'),
    url(r'^updates1/(?P<id>\d+)/$',  views.updates1, name='updates1'),
    url(r'^views2', views.shows2, name='views2'),
    url(r'^(?P<id>\d+)/edits2/$', views.edits2, name='edits2'), 
    url(r'^deletes2/(?P<id>\d+)/$', views.deletes2, name='deletes2'),
    url(r'^updates2/(?P<id>\d+)/$',  views.updates2, name='updates2'),
    url(r'^views3', views.shows3, name='views3'),
    url(r'^(?P<id>\d+)/edits3/$', views.edits3, name='edits3'), 
    url(r'^deletes3/(?P<id>\d+)/$', views.deletes3, name='deletes3'),
    url(r'^updates3/(?P<id>\d+)/$',  views.updates3, name='updates3'),
    url(r'^views4', views.shows4, name='views4'),
    url(r'^(?P<id>\d+)/edits4/$', views.edits4, name='edits4'), 
    url(r'^deletes4/(?P<id>\d+)/$', views.deletes4, name='deletes4'),
    url(r'^updates4/(?P<id>\d+)/$',  views.updates4, name='updates4'),

]